default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV["MYSQL_USERNAME"] %>
  password: <%= ENV["MYSQL_PASSWORD"] %>
  host: 127.0.0.1

development:
  <<: *default
  database: stray_development

test:
  <<: *default
  database: stray_test

production:
  <<: *default
  database: stray_production
