ActionController::InvalidAuthenticityToken:
  status: bad_request
  message: invalid csrf_token.
ApplicationController::NoToken:
  status: bad_request
  message: invalid token.
User::DuplicateEquips:
  status: bad_request
  message: 装備が重複しています。
MessagesController::EmptyRequest:
  status: bad_request
  message: メッセージが空だよ
User::AlreadyUsed:
  status: bad_request
  message: このユーザ名は使われています。
User::EmptyName:
  status: bad_request
  message: 名前が空です。
User::EmptyPassword:
  status: bad_request
  message: パスワードが空です。
User::NotFound:
  status: not_found
  message: ユーザ名かパスワードが違います。
User::Status::CannotSwitchDungeon:
  status: bad_request
  message: ダンジョンIDか、階層指定が不正です。
User::Item::InsufficientRank:
  status: bad_request
  message: 所持アイテムの最大強化値以上に強化はできません。
User::Item::InsufficientCoin:
  status: bad_request
  message: コインが足りません。
SessionId::Expired:
  status: bad_request
  message: 別ウィンドウでゲームが開始されました。
